---
- name: Terminate EC2 instances
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    aws_region: {{ region }}
    ec2_tags:
      Name: {{ group }}
      
  tasks:
    - name: Find EC2 Facts
      ec2_remote_facts:
        region: "{{ region }}"
      register: ec2_facts

      # (-) is used to stip white spaces
      # http://jinja.pocoo.org/docs/dev/templates/#whitespace-control
    - name: Filter EC2 instances
      set_fact:
        ec2_instances: |
          {% set instances = [] %}
          {% for item in ec2_facts.instances if item.tags == ec2_tags and item.state == 'running' -%}
            {{ instances.append(item.id) }}
          {%- endfor %}
          {{ instances }}
    - name: Terminate EC2 server
      ec2:
        region: "{{ aws_region }}"
        instance_ids: "{{ item }}"
        state: 'absent'
      with_items: "{{ ec2_instances }}"

## Terminates an EC2 instance

- include_vars: vars/main.yml

- meta: refresh_inventory

- name: Get EC2 instance IDs
  run_once: true
  ec2_facts:
    filters:
      "tag:Type": "{{ demo.instance_tags.name }}"
      "tag:Role": "{{ demo.instance_tags.name }}"
    region: "{{ demo.region }}"
  register: instances

- name: display instances
  run_once: true
  debug:
    var: instances

- name: Remove registered instances
  run_once: true
  ec2:
    state: absent
    wait: true
    instance_ids: "{{instances|json_query('instances[*].id')}}"
    region: "{{ demo.region }}"
  when: instances

