---
## Gather and report systemd units on the target host.

# Make sure we have an EC2 instance running.
- hosts: localhost
  roles: 
    - provision-instance

# Gather systemd units.
- hosts: ec2
  gather_facts: False

  tasks:
    - name: Output system units and states
      systemd-units: 
      register: result

    - debug: msg=result    
