---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - include_vars: roles/provision-instance/defaults/main.yml

    - meta: refresh_inventory

    - name: Gather EC2 facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_tags.name }}"
      register: ec2
    - debug: msg="Instance_id is {{ ec2.instances[0]['instance_id'] }}"

    - name: Terminate EC2 Instance(s)
      ec2:
        instance_ids: "{{ item.instance_id }}"
        region: "{{ region }}"
        state: "absent"
        wait: true
        wait_timeout: 600
      with_items: "{{ ec2.instances }}"

    - name: Remove the security group
      ec2_group:
        name: "{{ group }}"
        state: absent
        region: "{{ region }}"
      register: ec2_group
    - debug: msg="Security group {{ ec2_group.group_id }} has been removed"

    - name: Remove the alarm
      ec2_metric_alarm:
        state: absent
        region: "{{ region }}"
        name: "recover-modus"

