---
## Provision an EC2 instance.

- meta: refresh_inventory

- name: Create a security group
  ec2_group:
    name: "{{ group }}"
    description: The Modus security group
    region: "{{ region }}"
    tags:
      Name: "{{ group }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: "All ssh from any"
  register: ec2_group
- debug: msg="Security group {{ ec2_group.group_id }} has rules {{ ec2_group.ip_permissions }}"

- name: Launch an instance
  ec2:
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    region: "{{ region }}"
    group: "{{ group }}"
    exact_count: 1
    count_tag:
      Name: "{{ instance_tags.name }}"
    instance_tags:
      Name: "{{ instance_tags.name }}"
    volumes:
      - device_name: "/dev/sda1"
        volume_size: 16
        delete_on_termination: true
    wait: true
    wait_timeout: 600
  register: ec2
- debug: msg="Instance {{ instance_tags.name }} metadata is {{ ec2 }}"

- name: Add the newly created host to inventory
  add_host:
    name: "{{ item.public_ip }}"
    groups: "{{ group }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"

